name: 'build-test'

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkoit repository
        uses: actions/checkout@v4
        
      - name: Install
        run: |
          npm install

      - name: Verify
        run: |
          npm run all

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkoit repository
        uses: actions/checkout@v4

      - name: Run Action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-webhook-url: https://automation.atlassian.com/pro/hooks/666
